//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKUSponsionsService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public string Matrikelnumber { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Curricula { get; set; }
        public string MasterThesis { get; set; }
    }
}
