//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKUSponsionsService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JKUSponsionsServiceEntities1 : DbContext
    {
        public JKUSponsionsServiceEntities1()
            : base("name=JKUSponsionsServiceEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Representative> Representative { get; set; }
        public virtual DbSet<Event_Member> Event_Member { get; set; }
        public virtual DbSet<Event_Representative> Event_Representative { get; set; }
    }
}
